//
//  SearchPresenter.swift
//  LandmarkRemark
//
//  Created by Mira Kim on 21/05/19.
//  Copyright (c) 2019 mira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic
{
    func presentNotes(_ notes: [NoteCellModel]?)
    func presentSearchResult(_ result: [NoteCellModel]?)
}

class SearchPresenter: SearchPresentationLogic
{
    weak var viewController: SearchDisplayLogic?

    // MARK: Do something

    func presentNotes(_ notes: [NoteCellModel]?)
    {
        viewController?.displayNotes(viewModel: notes ?? [NoteCellModel]())
    }
    
    func presentSearchResult(_ result: [NoteCellModel]?) {
        viewController?.displayNotes(viewModel: result ?? [NoteCellModel]())
    }
}
