//
//  SearchRouter.swift
//  LandmarkRemark
//
//  Created by Mira Kim on 21/05/19.
//  Copyright (c) 2019 mira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchRoutingLogic
{
    func routeUnwindToMap(segue: UIStoryboardSegue?)
}

protocol SearchDataPassing
{
  var dataStore: SearchDataStore? { get }
}

class SearchRouter: NSObject, SearchRoutingLogic, SearchDataPassing
{
    weak var viewController: SearchViewController?
    var dataStore: SearchDataStore?

    // MARK: Routing

    func routeUnwindToMap(segue: UIStoryboardSegue?)
    {
        guard let segue = segue else {
            return
        }
        
        let destinationVC = segue.destination as! MapViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToMap(source: dataStore!, destination: &destinationDS)
        
    }

    // MARK: Passing data

    func passDataToMap(source: SearchDataStore, destination: inout MapDataStore) {
        // nothing is selected so ignore
        guard let selectedNote = source.selectedNote else {
            return
        }
        
        let viewModel = NoteConverter.convertCellForMap(selectedNote)
        destination.noteToShow = viewModel
        
    }
}
