//
//  AddNoteInteractor.swift
//  LandmarkRemark
//
//  Created by Mira Kim on 18/05/19.
//  Copyright (c) 2019 mira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddNoteBusinessLogic
{
    func saveNote(_ text: String)
    
}

protocol AddNoteDataStore
{
    var longitude: Double? { get set }
    var latitude: Double? { get set }
    
}

class AddNoteInteractor: AddNoteBusinessLogic, AddNoteDataStore
{
    var presenter: AddNotePresentationLogic?
    var worker: AddNoteWorkerProtocol?
    
    var longitude: Double?
    var latitude: Double?
    
    var localStorage = LocalStore()
    
    func saveNote(_ text: String) {
        if text.isEmpty {
            presenter?.presentError(withType: .noText)
            return
        }
        
        worker = AddNoteWorker()
        
        guard let locationLatitude = latitude, let locationLongitude = longitude else {
            LoggingUtility.debug("Location doesn't exist")
            presenter?.presentError(withType: .noLocation)
            return
        }
        
        guard let username = localStorage.username else {
            LoggingUtility.debug("Username is not set")
            presenter?.presentError(withType: .noUsername)
            return
        }
        
        let note = Note.Dto(text: text,
                            username: username,
                            latitude: locationLatitude,
                            longitude: locationLongitude,
                            datetime: DateUtility.currentDateTimeInUnix())

        
        worker?.addNewNote(note, completion: { (error) in
            if let error = error {
                self.presenter?.presentError(withType: .error(error))
                return
            }
            self.presenter?.presentSuccess()
        })
    }
    
}
