//
//  MapRouter.swift
//  LandmarkRemark
//
//  Created by Mira Kim on 17/05/19.
//  Copyright (c) 2019 mira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MapRoutingLogic
{
    func routeToAddNote(segue: UIStoryboardSegue)
}

protocol MapDataPassing
{
  var dataStore: MapDataStore? { get }
}

class MapRouter: NSObject, MapRoutingLogic, MapDataPassing
{
    weak var viewController: MapViewController?
    var dataStore: MapDataStore?

    // MARK: Routing

    func routeToAddNote(segue: UIStoryboardSegue)
    {
        let navController = segue.destination as! UINavigationController
        let destinationVC = navController.viewControllers.first as! AddNoteViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToAddNote(source: dataStore!, destination: &destinationDS)

    }
  
  // MARK: Passing data
  
    /// Attaches the current location to the new note
    func passDataToAddNote(source: MapDataStore, destination: inout AddNoteDataStore)
    {
        destination.latitude = source.latitude
        destination.longitude = source.longitude
    }
}
