//
//  MapModels.swift
//  LandmarkRemark
//
//  Created by Mira Kim on 17/05/19.
//  Copyright (c) 2019 mira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

enum Note
{
  // MARK: Use cases - DTO for Firestore
    
    struct Dto: Codable, Equatable
    {
        var text: String
        var username: String
        var latitude: Double
        var longitude: Double
        var datetime: Double    // timeIntervalSince1970
    }
    
}


// MARK: Use cases - ViewModel for map annotation (pin)

class NoteViewModel: NSObject, MKAnnotation {
    
    let text: String
    let username: String
    let latitude: Double
    let longitude: Double
    let createdAt: Date      // probably hidden from view
    
    // MARK: MKAnnotation
    
    var title: String? {
        return username
    }
    
    let subtitleMaxLength = 15
    var subtitle: String? {
        if text.count <= subtitleMaxLength {
            return text
        }
        let shortened = text.prefix(subtitleMaxLength)
        return "\(shortened).."
    }
    
    var coordinate: CLLocationCoordinate2D {
        return CLLocationCoordinate2D(latitude: latitude, longitude: longitude)
    }
    
    // TODO: show different color for user's own notes?
    var markerTintColor: UIColor {
        return .red
    }
    
    // MARK: Initialization
    
    init(text: String, username: String, latitude: Double, longitude: Double, createdAt: Date) {
        self.text = text
        self.username = username
        self.latitude = latitude
        self.longitude = longitude
        self.createdAt = createdAt
        
        super.init()
    }
}


// MARK: Use cases - ViewModel for table view

struct NoteCellModel {
    var title: String
    var subtitle: String
    var latitude: Double
    var longitude: Double
    var createdAt: Date     // hidden but included
}
